---
Standalone:
  hosts:
    standalone:
      ansible_host: 192.168.24.1
      canonical_hostname: standalone.localdomain
      ctlplane_hostname: standalone.ctlplane.localdomain
      ctlplane_ip: 192.168.24.1
  vars:
    tripleo_role_name: Standalone
ceph_osd:
  children:
    Standalone: {}
  vars:
    ansible_ssh_user: root
ceph_mgr:
  children:
    Standalone: {}
  vars:
    ansible_ssh_user: root
ceph_client:
  children:
    Standalone: {}
  vars:
    ansible_ssh_user: root
ceph_mon:
  children:
    Standalone: {}
  vars:
    ansible_ssh_user: root
nova_libvirt:
  children:
    Standalone: {}
  vars:
    ansible_ssh_user: root
