---
# Copyright 2022 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Revert LVM snapshots to main disks
  when:
    - ansible_facts.lvm is defined
    - ansible_facts.lvm.lvs is defined
    - ansible_facts.lvm.vgs is defined
    - ansible_facts.lvm.vgs.vg is defined
  block:
    - name: Revert audit snapshot volume
      command: lvconvert --merge /dev/vg/ss_audit
      when: ansible_facts.lvm.lvs.ss_audit is defined

    - name: Revert home snapshot volume
      command: lvconvert --merge /dev/vg/ss_home
      when: ansible_facts.lvm.lvs.ss_home is defined

    - name: Revert log snapshot volume
      command: lvconvert --merge /dev/vg/ss_log
      when: ansible_facts.lvm.lvs.ss_log is defined

    - name: Revert root snapshot volume
      command: lvconvert --merge /dev/vg/ss_root
      when: ansible_facts.lvm.lvs.ss_root is defined

    - name: Revert srv snapshot volume
      command: lvconvert --merge /dev/vg/ss_srv
      when: ansible_facts.lvm.lvs.ss_srv is defined

    - name: Revert var snapshot volume
      command: lvconvert --merge /dev/vg/ss_var
      when: ansible_facts.lvm.lvs.ss_var is defined
  tags:
    - revert_snapshots

- name: Delete the lv_snapshot volume if it exists
  command: lvremove -f /dev/vg/lv_snapshot
  when:
    - ansible_facts.lvm is defined
    - ansible_facts.lvm.lvs is defined
    - ansible_facts.lvm.vgs is defined
    - ansible_facts.lvm.vgs.vg is defined
    - ansible_facts.lvm.lvs.lv_snapshot is defined
    - ansible_facts.lvm.lvs.lv_snapshot.size_g|float >= 8.00
  tags:
    - create_snapshots
    - remove_lv_snapshot

- name: Remove LVM snapshots
  when:
    - ansible_facts.lvm is defined
    - ansible_facts.lvm.lvs is defined
    - ansible_facts.lvm.vgs is defined
    - ansible_facts.lvm.vgs.vg is defined
  block:
    - name: Clean home snapshot volume
      command: lvremove -f /dev/vg/ss_home
      when: ansible_facts.lvm.lvs.ss_home is defined

    - name: Clean log snapshot volume
      command: lvremove -f /dev/vg/ss_log
      when: ansible_facts.lvm.lvs.ss_log is defined

    - name: Clean root snapshot volume
      command: lvremove -f /dev/vg/ss_root
      when: ansible_facts.lvm.lvs.ss_root is defined

    - name: Clean srv snapshot volume
      command: lvremove -f /dev/vg/ss_srv
      when: ansible_facts.lvm.lvs.ss_srv is defined

    - name: Clean var snapshot volume
      command: lvremove -f /dev/vg/ss_var
      when: ansible_facts.lvm.lvs.ss_var is defined

    - name: Clean audit snapshot volume
      command: lvremove -f /dev/vg/ss_audit
      when: ansible_facts.lvm.lvs.ss_audit is defined
  tags:
    - create_snapshots
    - remove_snapshots

- name: Read Services running on the host
  command: puppet lookup --explain 'service_names'
  when: tripleo_snapshot_revert_snapshot_inactive_nodes|bool
  register: services_enabled
  changed_when: false
  failed_when: false
  tags:
    - create_snapshots

- name: Take out the node from Pacemaker cluster before taking a snapshot
  command: pcs cluster stop --request-timeout={{ tripleo_snapshot_revert_pcs_timeout }}
  when:
    - tripleo_snapshot_revert_snapshot_inactive_nodes|bool
    - services_enabled is defined
    - '"pacemaker" in services_enabled.stdout'
  tags:
    - create_snapshots

- name: Create lvm snapshot if there are at least 8GB of free space in the vg volumegroup
  when:
    - ansible_facts.lvm is defined
    - ansible_facts.lvm.lvs is defined
    - ansible_facts.lvm.vgs is defined
    - ansible_facts.lvm.vgs.vg is defined
    - ansible_facts.lvm.vgs.vg.free_g|float >= 8.00
  block:
    - name: Create audit snapshot volume
      command: lvcreate -s -n ss_audit -L {{ tripleo_snapshot_revert_audit_size }} /dev/vg/lv_audit
      when: ansible_facts.lvm.lvs.lv_audit is defined

    - name: Create home snapshot volume
      command: lvcreate -s -n ss_home -L {{ tripleo_snapshot_revert_home_size }} /dev/vg/lv_home
      when: ansible_facts.lvm.lvs.lv_home is defined

    - name: Create log snapshot volume
      command: lvcreate -s -n ss_log -L {{ tripleo_snapshot_revert_log_size }} /dev/vg/lv_log
      when: ansible_facts.lvm.lvs.lv_log is defined

    - name: Create root snapshot volume
      command: lvcreate -s -n ss_root -L {{ tripleo_snapshot_revert_root_size }} /dev/vg/lv_root
      when: ansible_facts.lvm.lvs.lv_root is defined

    - name: Create srv snapshot volume
      command: lvcreate -s -n ss_srv -L {{ tripleo_snapshot_revert_srv_size }} /dev/vg/lv_srv
      when: ansible_facts.lvm.lvs.lv_srv is defined

    - name: Create var snapshot volume
      command: lvcreate -s -n ss_var -L {{ tripleo_snapshot_revert_var_size }} /dev/vg/lv_var
      when: ansible_facts.lvm.lvs.lv_var is defined
  tags:
    - create_snapshots

- name: Pacemaker management
  when:
    - services_enabled is defined
    - tripleo_snapshot_revert_snapshot_inactive_nodes|bool
    - "'pacemaker' in services_enabled.stdout"
  block:
    - name: Add the node to the pacemaker cluster
      command: pcs cluster start

    - name: Wait until pacemaker has Galera up&running
      shell: /var/lib/container-config-scripts/pacemaker_wait_bundle.sh galera galera-bundle Master
      when: "'mysql' in services_enabled.stdout"
  tags:
    - create_snapshots
