---
driver:
  name: podman

log: true

platforms:
  - name: ubi8
    hostname: ubi8
    image: ubi8/ubi-init
    registry:
      url: registry.access.redhat.com
    dockerfile: Dockerfile
    pkg_extras: python*setuptools
    command: >-
      /sbin/init &&
      /bin/mkdir -p /var/run/dbus &&
      /usr/bin/dbus-uuidgen > /var/lib/dbus/machine-id &&
      /usr/bin/dbus-daemon --config-file=/usr/share/dbus-1/system.conf
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
      - /etc/pki/rpm-gpg:/etc/pki/rpm-gpg
      - /opt/yum.repos.d:/etc/yum.repos.d:rw
    privileged: true
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
    ulimits: &ulimit
      - host

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          ubi8:
            ansible_python_interpreter: /usr/bin/python3
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
    ANSIBLE_ROLES_PATH: "${ANSIBLE_ROLES_PATH:-/usr/share/ansible/roles}:${HOME}/zuul-jobs/roles"
    ANSIBLE_LIBRARY: "${ANSIBLE_LIBRARY:-/usr/share/ansible/plugins/modules}"
    ANSIBLE_FILTER_PLUGINS: "${ANSIBLE_FILTER_PLUGINS:-/usr/share/ansible/plugins/filter}"
    ANSIBLE_ACTION_PLUGINS: "${ANSIBLE_ACTION_PLUGINS:-/usr/share/ansible/plugins/action}"

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
