---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Check valid input for tripleo_ovs_dpdk_pmd_core_list
  fail:
    msg: "List of PMD cores cannot be empty - tripleo_ovs_dpdk_pmd_core_list"
  when: not tripleo_ovs_dpdk_pmd_core_list|string or tripleo_ovs_dpdk_pmd_core_list == 'null'

- name: Apply PMD cores config
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: pmd-cpu-mask
    value: "{{ tripleo_ovs_dpdk_pmd_core_list | cpu_mask }}"
  when: tripleo_ovs_dpdk_pmd_core_list|string

- name: Set DPDK lcores config
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: dpdk-lcore-mask
    value: "{{ tripleo_ovs_dpdk_lcore_list | cpu_mask }}"
  when: tripleo_ovs_dpdk_lcore_list|string

- name: Remove DPDK lcores config
  openvswitch_db:
    state: absent
    table: open_vswitch
    record: .
    col: other_config
    key: dpdk-lcore-mask
  when: not tripleo_ovs_dpdk_lcore_list|string or tripleo_ovs_dpdk_lcore_list == 'null'

- name: Add memory channels to dpdk extra
  set_fact:
    tripleo_ovs_dpdk_extra_internal: "{{ tripleo_ovs_dpdk_extra }} -n {{ tripleo_ovs_dpdk_memory_channels }}"

- name: Apply DPDK extra
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: dpdk-extra
    value: "'{{ tripleo_ovs_dpdk_extra_internal }}'"

- name: Apply socket-mem and socket-limit config
  block:
    - openvswitch_db:
        table: open_vswitch
        record: .
        col: other_config
        key: dpdk-socket-mem
        value: "{{ tripleo_ovs_dpdk_socket_memory }}"

    - openvswitch_db:
        table: open_vswitch
        record: .
        col: other_config
        key: dpdk-socket-limit
        value: "{{ tripleo_ovs_dpdk_socket_memory }}"
  when: tripleo_ovs_dpdk_socket_memory|string

- name: Remove DPDK socket-mem and socket-limit config
  block:
    - openvswitch_db:
        state: absent
        table: open_vswitch
        record: .
        col: other_config
        key: dpdk-socket-mem

    - openvswitch_db:
        state: absent
        table: open_vswitch
        record: .
        col: other_config
        key: dpdk-socket-limit
  when: not tripleo_ovs_dpdk_socket_memory|string or tripleo_ovs_dpdk_socket_memory == 'null'

- name: Apply Revalidator threads config
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: n-revalidator-threads
    value: "{{ tripleo_ovs_dpdk_revalidator_cores }}"
  when: tripleo_ovs_dpdk_revalidator_cores|string

- name: Remove Revalidator threads config
  openvswitch_db:
    state: absent
    table: open_vswitch
    record: .
    col: other_config
    key: n-revalidator-threads
  when: not tripleo_ovs_dpdk_revalidator_cores|string

- name: Set Handler threads config
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: n-handler-threads
    value: "{{ tripleo_ovs_dpdk_handler_cores }}"
  when: tripleo_ovs_dpdk_handler_cores|string

- name: Remove Handler threads config
  openvswitch_db:
    state: absent
    table: open_vswitch
    record: .
    col: other_config
    key: n-handler-threads
  when: not tripleo_ovs_dpdk_handler_cores|string

- name: Set EMC Insertion Probability config
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: emc-insert-inv-prob
    value: "{{ tripleo_ovs_dpdk_emc_insertion_probablity }}"
  when: tripleo_ovs_dpdk_emc_insertion_probablity|string

- name: Remove EMC Insertion Probability config
  openvswitch_db:
    state: absent
    table: open_vswitch
    record: .
    col: other_config
    key: emc-insert-inv-prob
  when: not tripleo_ovs_dpdk_emc_insertion_probablity|string

- name: Enable TSO in datapath
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: userspace-tso-enable
    value: "{{ tripleo_ovs_dpdk_enable_tso }}"
  when: tripleo_ovs_dpdk_enable_tso|bool

- name: Disable TSO in datapath
  openvswitch_db:
    state: absent
    table: open_vswitch
    record: .
    col: other_config
    key: userspace-tso-enable
  when: not tripleo_ovs_dpdk_enable_tso|bool

- name: Enable postcopy support
  when: tripleo_ovs_dpdk_vhost_postcopy_support|bool
  block:
    - name: Enable vhost-postcopy-support
      openvswitch_db:
        table: open_vswitch
        record: .
        col: other_config
        key: vhost-postcopy-support
        value: "{{ tripleo_ovs_dpdk_vhost_postcopy_support }}"
    - name: Disable mlockall in ovs
      replace:
        path: '/etc/sysconfig/openvswitch'
        regexp: '^OPTIONS.*'
        replace: 'OPTIONS="{{ tripleo_ovs_dpdk_vhost_postcopy_ovs_options }}"'

- name: Disable postcopy support
  when: not tripleo_ovs_dpdk_vhost_postcopy_support|bool
  block:
    - name: Disable vhost-postcopy-support
      openvswitch_db:
        state: absent
        table: open_vswitch
        record: .
        col: other_config
        key: vhost-postcopy-support
    - name: Return ovs OPTIONS to default
      replace:
        path: '/etc/sysconfig/openvswitch'
        regexp: '^OPTIONS.*'
        replace: 'OPTIONS=""'

- name: Enable DPDK OVS PMD Auto Load Balance
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: pmd-auto-lb
    value: "{{ tripleo_ovs_dpdk_pmd_auto_lb }}"
  when: tripleo_ovs_dpdk_pmd_auto_lb|bool

- name: Disable DPDK OVS PMD Auto Load Balance
  openvswitch_db:
    state: absent
    table: open_vswitch
    record: .
    col: other_config
    key: pmd-auto-lb
  when: not tripleo_ovs_dpdk_pmd_auto_lb|bool

- name: Set minimum PMD thread load threshold
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: pmd-auto-lb-load-threshold
    value: "{{ tripleo_ovs_dpdk_pmd_load_threshold }}"
  when: tripleo_ovs_dpdk_pmd_load_threshold|string

- name: Remove minimum PMD thread load threshold
  openvswitch_db:
    state: absent
    table: open_vswitch
    record: .
    col: other_config
    key: pmd-auto-lb-load-threshold
  when: not tripleo_ovs_dpdk_pmd_load_threshold|string

- name: Set PMD load variance improvement threshold
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: pmd-auto-lb-improvement-threshold
    value: "{{ tripleo_ovs_dpdk_pmd_improvement_threshold }}"
  when: tripleo_ovs_dpdk_pmd_improvement_threshold|string

- name: Remove PMD load variance improvement threshold
  openvswitch_db:
    state: absent
    table: open_vswitch
    record: .
    col: other_config
    key: pmd-auto-lb-improvement-threshold
  when: not tripleo_ovs_dpdk_pmd_improvement_threshold|string

- name: Set PMD auto load balancing interval
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: pmd-auto-lb-rebal-interval
    value: "{{ tripleo_ovs_dpdk_pmd_rebal_interval }}"
  when: tripleo_ovs_dpdk_pmd_rebal_interval|string

- name: Remove PMD auto load balancing interval
  openvswitch_db:
    state: absent
    table: open_vswitch
    record: .
    col: other_config
    key: pmd-auto-lb-rebal-interval
  when: not tripleo_ovs_dpdk_pmd_rebal_interval|string

- name: Set PMD maximum sleep time
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: pmd-maxsleep
    value: "{{ tripleo_ovs_dpdk_pmd_sleep_max }}"
  when: tripleo_ovs_dpdk_pmd_sleep_max|string

- name: Remove PMD maximum sleep time
  openvswitch_db:
    state: absent
    table: open_vswitch
    record: .
    col: other_config
    key: pmd-maxsleep
  when: not tripleo_ovs_dpdk_pmd_sleep_max|string
