---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# All variables intended for modification should be placed in this file.
tripleo_backup_and_restore_hide_sensitive_logs: "{{ hide_sensitive_logs | default(true) }}"
tripleo_backup_and_restore_debug: "{{ ((ansible_verbosity | int) >= 2) | bool }}"
tripleo_controller_group_name: "{{ controller_group_name | default('Controller') }}"

# Set the container command line entry-point
tripleo_container_cli: "{{ container_cli | default('podman') }}"
tripleo_container_cli_flags: ""
# Stop and start all running services before backup is ran.
tripleo_backup_and_restore_service_manager: true

# If this is false, backup of the overcloud is taken by stopping it completely. Enable it to do a
# backup stopping only one node at a time, maintaining the controller active during the backup duration.
tripleo_backup_and_restore_enable_snapshots: true

# Set the name of the mysql container
tripleo_backup_and_restore_mysql_container: mysql

# Default name for the Undercloud mysql DB backup file
tripleo_backup_and_restore_mysql_backup_file: "openstack-backup-mysql.sql"

# Default name for the Undercloud mysql DB grants file
tripleo_backup_and_restore_mysql_grants_file: "openstack-backup-mysql-grants.sql"

# All variables within this role should have a prefix of "tripleo_backup_and_restore"
# By default this should be the Undercloud node
tripleo_backup_and_restore_server: 192.168.24.1
tripleo_backup_and_restore_shared_storage_folder: /ctl_plane_backups
tripleo_backup_and_restore_shared_storage_subfolders: []
tripleo_backup_and_restore_clients_nets: ['192.168.24.0/24', '10.0.0.0/24', '172.16.0.0/24']
tripleo_backup_and_restore_rear_simulate: false
tripleo_backup_and_restore_using_uefi_bootloader: 0
tripleo_backup_and_restore_exclude_paths_common: ['/data/*', '/tmp/*', '{{ tripleo_backup_and_restore_shared_storage_folder }}/*']
tripleo_backup_and_restore_exclude_paths_controller_non_bootstrapnode: false
tripleo_backup_and_restore_exclude_paths_controller: ['/var/lib/mysql/*']
tripleo_backup_and_restore_exclude_paths_compute: ['/var/lib/nova/instances/*']
tripleo_backup_and_restore_hiera_config_file: "/etc/puppet/hiera.yaml"

# This var is a dictionary of the configuration of the /etc/rear/local.conf
# The key:value will be interpreted as key=value on the configuration file.
# To set that the value is a string, it needs to be single quoted followed by
# double quoted as it will be interpreted by BASH.
tripleo_backup_and_restore_local_config:
  ISO_DEFAULT: '"automatic"'
  OUTPUT: ISO
  BACKUP: NETFS
  BACKUP_PROG_COMPRESS_OPTIONS: '( --gzip)'
  BACKUP_PROG_COMPRESS_SUFFIX: '".gz"'
  OUTPUT_URL: "{{ tripleo_backup_and_restore_output_url }}"
  ISO_PREFIX: "{{ tripleo_backup_and_restore_hostname.stdout }}"
  BACKUP_URL: "{{ tripleo_backup_and_restore_backup_url }}"
  BACKUP_PROG_CRYPT_ENABLED: "{{ tripleo_backup_and_restore_crypt_backup_enabled | default(false) }}"
  BACKUP_PROG_CRYPT_KEY: "{{ tripleo_backup_and_restore_crypt_backup_password | default('REPLACE_ME') }}"

# This var is used to define the commands to be run for preparing the network
# during the restoration phase. Because ReaR does not support ovs, it is required
# to setup the network for connecting to the backup node.
# This is configured on /etc/rear/local.conf
# as an example
# ('ip l a br-ex type bridge' 'ip l s ens3 up' 'ip l s br-ex up' 'ip l s ens3 master br-ex' 'dhclient br-ex')
tripleo_backup_and_restore_network_preparation_commands: "()"

# This var is a dictionary of the configuration of the /etc/rear/rescue.conf
# The key:value will be interpreted as key=value on the configuration file.
# To set that the value is a string, it needs to be single quoted followed by
# double quoted as it will be interpreted by BASH.
tripleo_backup_and_restore_rescue_config: {}

tripleo_backup_and_restore_output_url: "nfs://{{ tripleo_backup_and_restore_server }}{{ tripleo_backup_and_restore_shared_storage_folder }}"
tripleo_backup_and_restore_backup_url: "nfs://{{ tripleo_backup_and_restore_server }}{{ tripleo_backup_and_restore_shared_storage_folder }}"

# Ceph authentication backup file
tripleo_backup_and_restore_ceph_auth_file: "ceph_auth_export.bak"

# Ceph backup file
tripleo_backup_and_restore_ceph_backup_file: "/var/lib/ceph.tar.gz"

# Ceph directory to back up
tripleo_backup_and_restore_ceph_path: "/var/lib/ceph"

# If there is a firewalld active, setup the zone where the NFS server ports need to be opened
tripleo_backup_and_restore_firewalld_zone: "libvirt"

# The ReaR rpm installs a cronjob at 1:30 each day by default. This variable deactivate that behaviour.
tripleo_backup_and_restore_remove_default_cronjob: true

# Skip the ping test to the server on rear setup
tripleo_backup_and_restore_skip_server_test: false

# How many seconds do we want to wait fir pcs cluster stop to finish
tripleo_backup_and_restore_pcs_timeout: 3600

# Date argument to get the string of the backup
tripleo_backup_and_restore_date_argument: '%Y%m%d%H%M'

# Enable historical backups
tripleo_backup_and_restore_historical: true

# Cron programming, by default, run cron weekly at midnight on Sundays
tripleo_backup_and_restore_cron: "0 0 * * 0"

# The user that will run the backup command. If empty, root will run the backup command
tripleo_backup_and_restore_cron_user: "stack"

# Any extra parameters that will be added to the backup command when it is executed by cron
tripleo_backup_and_restore_cron_extra: ""

# The role which handles the ceph on the controllers
tripleo_backup_and_restore_ceph_mon_role: "ceph_mon"

# The cephadm path
tripleo_backup_and_restore_cephadm_path: "/usr/sbin/cephadm"

# The name of the node to restore
tripleo_backup_and_restore_overcloud_restore_name: undercloud

# Ironic images path
tripleo_backup_and_restore_ironic_images_path: "/var/lib/ironic/images"

# Restore retries
tripleo_backup_and_restore_restore_retries: 300

# Restore delay
tripleo_backup_and_restore_restore_delay: 10

# Galera retries
tripleo_backup_and_restore_galera_retries: 300

# Galera delay
tripleo_backup_and_restore_galera_delay: 10

# Ironic ubdirectory where the kernel and initrd are uploaded
backup_and_restore_history_path: ""

# Ceph cluster name
tripleo_backup_and_restore_ceph_cluster: "ceph"
tripleo_backup_and_restore_ceph_admin_keyring: "/etc/ceph/{{ tripleo_backup_and_restore_ceph_cluster }}.client.admin.keyring"
