---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Ensure profile directory exists
  file:
    path: "/etc/tuned/{{ tuned_profile }}"
    state: directory
  when:
    - (custom_profile is defined) and ((custom_profile | length) > 0)

- name: Create custom tuned profile
  copy:
    content: "{{ custom_profile }}"
    dest: "/etc/tuned/{{ tuned_profile }}/tuned.conf"
  when:
    - (custom_profile is defined) and ((custom_profile | length) > 0)

- name: Check tuned active profile
  slurp:
    src: "/etc/tuned/active_profile"
  register: tuned_active_profile

- name: Check Tuned Configuration file exists
  stat:
    path: "/etc/tuned/{{ tuned_profile }}-variables.conf"
  register: tuned_conf_stat_result

- name: Fail if tuned profile conf is absent but isolated cores is provided
  fail:
    msg: "Tuned profile conf file is not available to configure isolated cores"
  when:
    - tuned_isolated_cores
    - not tuned_conf_stat_result.stat.exists

- name: "Configure isolated cores for profile {{ tuned_profile }}"
  become: true
  lineinfile:
    dest: "/etc/tuned/{{ tuned_profile }}-variables.conf"
    regexp: '^isolated_cores=.*'
    line: 'isolated_cores={{ tuned_isolated_cores }}'
  when:
    - tuned_isolated_cores
    - tuned_conf_stat_result.stat.exists

- name: Enable tuned profile
  become: true
  command: >-
    tuned-adm profile {{ tuned_profile }}
  environment:
    PATH: "/bin:/usr/bin:/sbin:/usr/sbin"
  when:
    - ((tuned_active_profile['content'] | b64decode).strip()) != tuned_profile
