---

- hosts: all
  pre_tasks:
    - name: Set project path fact
      set_fact:
        tripleo_ansible_project_path: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/tripleo-ansible'].src_dir }}"

    - name: Ensure output dirs
      file:
        path: "{{ ansible_user_dir }}/zuul-output/logs"
        state: directory

    - name: Ensure pip is available
      include_role:
        name: ensure-pip

    - name: Setup bindep
      pip:
        name: "bindep"
        virtualenv: "{{ ansible_user_dir }}/test-python"
        virtualenv_command: "{{ ensure_pip_virtualenv_command }}"
        virtualenv_site_packages: true

    - name: Run bindep
      shell: |-
        . {{ ansible_user_dir }}/test-python/bin/activate
        {{ tripleo_ansible_project_path }}/scripts/bindep-install
      become: true

    - name: Ensure a recent version of pip is installed in virtualenv
      pip:
        name: "pip<20.3.0"
        virtualenv: "{{ ansible_user_dir }}/test-python"
        virtualenv_command: "{{ ensure_pip_virtualenv_command }}"
        state: latest

    - name: Setup test-python
      pip:
        requirements: "{{ tripleo_ansible_project_path }}/molecule-requirements.txt"
        virtualenv: "{{ ansible_user_dir }}/test-python"
        virtualenv_command: "{{ ensure_pip_virtualenv_command }}"
        virtualenv_site_packages: true
        extra_args: >-
          --constraint "{{ tripleo_ansible_project_path }}/ansible-requirements.txt"

    - name: Display test-python virtualenv package versions
      shell: |-
        . {{ ansible_user_dir }}/test-python/bin/activate
        pip freeze

    - name: Basic ci setup
      become: true
      block:
        - name: Ensure ci directories
          file:
            path: "/etc/ci"
            state: "directory"

        - name: Ensure ci mirror file
          file:
            path: "/etc/ci/mirror_info.sh"
            state: "touch"

        - name: Set an appropriate fs.file-max
          sysctl:
            name: fs.file-max
            value: 2048000
            sysctl_set: true
            state: present
            reload: true

        - name: Set container_manage_cgroup boolean
          seboolean:
            name: container_manage_cgroup
            state: true
            persistent: true
          failed_when: false

        - name: Create limits file for containers
          copy:
            content: |
              * soft nofile 102400
              * hard nofile 204800
              * soft nproc 2048
              * hard nproc 4096
            dest: /etc/security/limits.d/containers.conf

        - name: Copy repos directory to opt workspace
          copy:
            src: /etc/yum.repos.d
            dest: /opt/
            remote_src: true
            mode: "0777"

        # FIXME(Chandan): https://bugs.launchpad.net/tripleo/+bug/2015309
        - name: Downgrade gnupg2 to 2.3.3-2.el9.x86_64
          become: true
          ansible.builtin.shell: |
            sudo dnf -y downgrade gnupg2-2.3.3-2.el9.x86_64
          failed_when: false

        - name: Reset ssh connection
          meta: reset_connection
  tasks:
    - name: Get Ansible Galaxy roles
      command: >-
        {{ ansible_user_dir }}/test-python/bin/ansible-galaxy install
        -fr
        {{ tripleo_ansible_project_path }}/tripleo_ansible/ansible-role-requirements.yml
      environment:
        ANSIBLE_ROLES_PATH: "{{ tripleo_ansible_project_path }}/tripleo_ansible/roles.galaxy"

    - name: Get Ansible Galaxy collections
      command: >-
        {{ ansible_user_dir }}/test-python/bin/ansible-galaxy collection install
        -fr
        {{ tripleo_ansible_project_path }}/tripleo_ansible/requirements.yml
      environment:
        ANSIBLE_ROLES_PATH: "{{ tripleo_ansible_project_path }}/tripleo_ansible/roles.galaxy"
