---
# Copyright 2022 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Create Ceph Spec for Standalone Deployment
  hosts: undercloud
  gather_facts: false
  vars:
    osd_spec:
      data_devices:
        all: true
    tld_option: ""
  tasks:
    - name: Fail if tripleo_cephadm_first_mon_ip is undefined
      fail:
        msg: "--mon-ip (tripleo_cephadm_first_mon_ip) was not provided"
      when:
        - tripleo_cephadm_first_mon_ip is undefined
        - tripleo_cephadm_first_mon_ip | length == 0

    - name: Ensure ceph_spec_path is defined
      set_fact:
        ceph_spec_path: "{{ working_dir }}/generated_ceph_spec.yaml"
      when:
        - ceph_spec_path is undefined

    - name: Override osd_spec if osd_spec_path is provided
      set_fact:
        osd_spec: "{{ osd_spec_path_content | from_yaml }}"
      vars:
        osd_spec_path_content: "{{ lookup('file', osd_spec_path) }}"
      when:
        - osd_spec_path is defined
        - osd_spec_path | length > 0

    - name: Create Ceph spec for standalone deployment
      ceph_spec_bootstrap:
        new_ceph_spec: "{{ ceph_spec_path }}"
        osd_spec: "{{ osd_spec }}"
        mon_ip: "{{ tripleo_cephadm_first_mon_ip }}"
        standalone: True
        tld: "{{ tld_option }}"
