---
# Copyright 2022 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Overcloud Node ovs-dpdk Configuration
  hosts: allovercloud
  any_errors_fatal: true
  gather_facts: true

  # "socket_mem" and "pmd" are mandatory parameters
  vars:
    pmd: ''
    socket_mem: ''
    memory_channels: ''
    lcore: ''
    disable_emc: false
    enable_tso: false
    revalidator: ''
    handler: ''
    pmd_auto_lb: false
    pmd_load_threshold: ''
    pmd_improvement_threshold: ''
    pmd_rebal_interval: ''
    pmd_sleep_max: ''
    nova_postcopy: true
    tuned_profile: 'cpu-partitioning'

  pre_tasks:
    - name: Wait for provisioned nodes to boot
      wait_for_connection:
        timeout: 600
        delay: 10

  tasks:
    - name: ovs-dpdk role specific config block
      become: true
      block:
        - name: Set nova post copy for migration
          set_fact:
            tripleo_ovs_dpdk_vhost_postcopy_support: "{{ nova_postcopy }}"
          when: tuned_profile != 'realtime-virtual-host'

        - name: Disable nova post copy for migration
          set_fact:
            tripleo_ovs_dpdk_vhost_postcopy_support: false
          when: tuned_profile == 'realtime-virtual-host'

        - name: Set insertion probablity based on emc cache flag
          set_fact:
            tripleo_ovs_dpdk_emc_insertion_probablity: 0
          when: disable_emc|bool

        - name: Configure ovs-dpdk role params
          include_role:
             name: tripleo_ovs_dpdk
          vars:
            tripleo_ovs_dpdk_lcore_list: "{{ lcore }}"
            tripleo_ovs_dpdk_pmd_core_list: "{{ pmd }}"
            tripleo_ovs_dpdk_memory_channels: "{{ memory_channels }}"
            tripleo_ovs_dpdk_socket_memory: "{{ socket_mem }}"
            tripleo_ovs_dpdk_enable_tso: "{{ enable_tso }}"
            tripleo_ovs_dpdk_revalidator_cores: "{{ revalidator }}"
            tripleo_ovs_dpdk_handler_cores: "{{ handler }}"
            tripleo_ovs_dpdk_pmd_auto_lb: "{{ pmd_auto_lb }}"
            tripleo_ovs_dpdk_pmd_load_threshold: "{{ pmd_load_threshold }}"
            tripleo_ovs_dpdk_pmd_improvement_threshold: "{{ pmd_improvement_threshold }}"
            tripleo_ovs_dpdk_pmd_rebal_interval: "{{ pmd_rebal_interval }}"
            tripleo_ovs_dpdk_pmd_sleep_max: "{{ pmd_sleep_max }}"
