---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Overcloud Delete
  connection: "{{ (tripleo_target_host is defined) | ternary('ssh', 'local') }}"
  hosts: "{{ tripleo_target_host | default('localhost') }}"
  remote_user: "{{ tripleo_target_user | default(lookup('env', 'USER')) }}"
  gather_facts: "{{ (tripleo_target_host is defined) | ternary(true, false) }}"
  any_errors_fatal: true
  pre_tasks:
    - name: Check for required inputs
      fail:
        msg: >
          Input missing `{{ item }}`
      when:
        - hostvars[inventory_hostname][item] is undefined
      loop:
        - stack_name
  tasks:
    - name: Delete heat stack
      os_stack:
        name: "{{ stack_name }}"
        state: absent
      register: stack_delete
      until: stack_delete is success
      delay: 4
      retries: 16

    # NOTE (cloudnull): This is using the CLI command to delete a given container
    #                   because the os_object module does not yet handle recursive
    #                   deletes. Revise this when RFE 60449 is implemented.
    #                   https://github.com/ansible/ansible/issues/60449
    - name: Delete container and objects
      command: >
        openstack --os-cloud undercloud container delete "{{ item }}" --recursive
      failed_when:
        - container_objects.rc != 0
        - "'not found' not in container_objects.stderr | lower"
      changed_when:
        - "'not found' not in container_objects.stderr | lower"
      register: container_objects
      loop:
        - "{{ stack_name }}"
        - "{{ stack_name }}-messages"
        - "{{ stack_name }}-swift-rings"

  post_tasks:
    - name: Workflow notice
      debug:
        msg: Ansible workflow completed.

  tags:
    - tripleo-overcloud-delete
