---
# Copyright 2021 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
- name: Overcloud Node Network Config
  hosts: allovercloud
  any_errors_fatal: true
  gather_facts: false
  pre_tasks:
    - name: Wait for provisioned nodes to boot
      wait_for_connection:
        timeout: 600
        delay: 10
      connection: local
  roles:
    - role: tripleo_network_config
      vars:
        # The conditions here are when we want to apply the
        # NetworkConfig. They are:
        # - If tripleo_network_config_update is True
        # - Or the previous run of NetworkConfig failed.
        # - Or it has never run
        # This will match the prior behavior of when a Heat
        # SoftwareDeployment was used.
        # It also ensures the script does exist as a sine qua non
        # condition
        tripleo_network_config_update: True
