- name: Get controller network fixed IPs
  shell: |
    openstack port show -c fixed_ips -f json \
        octavia-health-manager-{{ canonical_hostname }}-listen-port
  delegate_to: undercloud
  changed_when: false
  register: port_fixed_ips

- name: Get router interfaces
  shell: |
    openstack router show -c interfaces_info -f json {{ lb_mgmt_prefix }}-router
  delegate_to: undercloud
  changed_when: false
  run_once: yes
  register: router_interfaces

- name: Set facts for router gateway
  set_fact:
    gateway: "{{ router_interfaces.stdout | from_json | json_query(query) | first }}"
  vars:
    query: "interfaces_info[?subnet_id=='{{ port_subnet_id }}'].ip_address"
    port_subnet_id: "{{ port_fixed_ips.stdout | from_json | json_query('fixed_ips[0].subnet_id') }}"

- name: Get subnets CIDRs
  shell: |
    openstack subnet show -c cidr -f value {{ lb_mgmt_prefix }}-{{ item }}-subnet
  delegate_to: undercloud
  changed_when: false
  run_once: yes
  register: cidrs
  loop: "{{ octavia_availability_zones | difference([octavia_controller_availability_zone]) }}"

- name: Create route file for o-hm0
  copy:
    dest: /etc/sysconfig/network-scripts/route-o-hm0
    content: |
      {% for cidr in cidrs.results %}
      {{ cidr.stdout }} via {{ gateway }}
      {% endfor %}
  become: yes

- name: Set o-hm0 up
  shell: |
    ifdown o-hm0
    ifup o-hm0
  become: yes
