---
- name: Define list of keys to search for in initial ceph conf file
  set_fact:
    keys_in_ceph_conf: []
    ceph_network_keys:
      - 'public_network'
      - 'cluster_network'
      - 'ms_bind_ipv4'
      - 'ms_bind_ipv6'

- name: Expand list of keys to include versions of themselves with spaces
  set_fact:
    ceph_network_keys: "{{ ceph_network_keys + [ key | regex_replace('_', ' ') ] }}"
  loop: "{{ ceph_network_keys }} "
  loop_control:
    loop_var: key

- name: Build list of underscored keys found in initial ceph conf file
  ignore_errors: true
  delegate_to: localhost
  set_fact:
    keys_in_ceph_conf: "{{ keys_in_ceph_conf + [ key | regex_replace(' ', '_') ] }}"
  vars:
    conf: "{{ tripleo_cephadm_bootstrap_conf }}"
    value: "{{ lookup('ini',
                       key ~ ' section=global default= file=' ~ conf) }}"
  when:
    - tripleo_cephadm_bootstrap_conf | default('') | length > 0
    - value | default('') | string | length > 0
  loop: "{{ ceph_network_keys }}"
  loop_control:
    loop_var: key

- name: Set public/cluster network and v4/v6 ms_bind unless already in ceph.conf
  command: |
    {{ tripleo_cephadm_ceph_cli }} config set global {{ item.key }} {{ item.value }}
  loop: "{{ net_data | dict2items }}"
  when:
    - item.value | length > 0
    - item.key not in keys_in_ceph_conf
  changed_when: false
  become: true
  vars:
    net_data: # these variables are usually passed via --extra-vars
      public_network: "{{ public_network | default('') | string }}"
      cluster_network: "{{ cluster_network | default('') | string }}"
      ms_bind_ipv4 : "{{ ms_bind_ipv4 | default('') | string }}"
      ms_bind_ipv6 : "{{ ms_bind_ipv6 | default('') | string }}"
