---

# Note: Previous versions of TripleO used log file with podman exec specific data
#       to provide health check execution results to sensubility. This serves for
#       cleanup of unneeded rsyslog configuration since sensubility is fetching
#       data straight from podman socket

- name: remove unneeded podman-related rsyslog configuration
  ansible.builtin.file:
    path: /etc/rsyslog.d/openstack-healthcheck.conf
    state: absent
  ignore_errors: yes
  register: rmcfg
- when: rmcfg is changed
  service:
    name: rsyslog
    state: restarted
