---
# inherits .config/molecule/config.yml
provisioner:
  playbooks:
    prepare: "${MOLECULE_SCENARIO_DIRECTORY}/../../resources/molecule/prepare.yml"
    cleanup: "${MOLECULE_SCENARIO_DIRECTORY}/../../resources/molecule/cleanup.yml"

scenario:
  test_sequence:
    - prepare
    - converge
    - check
    - cleanup

verifier:
  name: testinfra
