---
- name: Create httpd config and vhost
  vars:
    tripleo_httpd_vhost_user: 'ironic'
    tripleo_httpd_vhost_service_name: 'ironic'
    tripleo_httpd_vhost_servername: 'ipxe_vhost'
    tripleo_httpd_vhost_group: "{{ tripleo_httpd_vhost_user }}"
    tripleo_httpd_vhost_access_log_name: "{{ tripleo_httpd_vhost_servername }}"
    tripleo_httpd_vhost_document_root: '/var/lib/ironic/httpboot'
    tripleo_httpd_vhost_bind_port: 8088
    tripleo_httpd_vhost_options:
      - 'Indexes'
      - 'FollowSymLinks'
    tripleo_httpd_vhost_wsgi: false
    tripleo_httpd_vhost_ssl: false
  import_role:
    name: tripleo_httpd_vhost
