---
driver:
  name: podman

log: true

platforms:
  - name: centos7
    hostname: centos7
    image: centos:7
    dockerfile: Dockerfile
    pkg_extras: python-setuptools
    volumes:
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
    easy_install:
      - pip
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"

  - name: centos8
    hostname: centos8
    image: centos:8
    dockerfile: Dockerfile
    pkg_extras: python*-setuptools
    volumes:
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
    environment:
      <<: *env

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          all_nodes_extra_map_data: {}
          cloud_domain: localdomain
          cloud_names:
            cloud_name_ctlplane: standalone.ctlplane.localdomain
          container_cli: podman
          control_virtual_ip: 192.168.24.1
          ctlplane_ip: 192.168.24.2
          ctlplane_subnet_cidr: 24
          deploy_artifact_urls: ''
          deploy_identifier: '1564455089'
          deploy_steps_max: 6
          enable_internal_tls: false
          enabled_networks: []
          enabled_services:
            - keystone_admin_api
            - keystone_public_api
            - ca_certs
            - ceph_client
            - ceph_mds
            - ceph_mgr
            - ceph_mon
            - ceph_rgw
            - ceph_osd
            - certmonger_user
            - clustercheck
            - container_image_prepare
            - logrotate_crond
            - docker
            - docker_registry
            - glance_api
            - haproxy
            - iscsid
            - kernel
            - keystone
            - manila_api
            - manila_backend_cephfs
            - manila_scheduler
            - manila_share
            - memcached
            - mysql
            - mysql_client
            - neutron_api
            - neutron_plugin_ml2_ovn
            - nova_api
            - nova_compute
            - nova_conductor
            - nova_libvirt
            - nova_metadata
            - nova_migration_target
            - nova_scheduler
            - nova_vnc_proxy
            - ovn_controller
            - ovn_dbs
            - ovn_metadata
            - openstack_clients
            - oslo_messaging_notify
            - oslo_messaging_rpc
            - pacemaker
            - placement
            - podman
            - snmp
            - sshd
            - chrony
            - timezone
            - logrotate_tmpwatch
            - tripleo_firewall
            - tripleo_packages
            - tuned
          extraconfig:
            foo: bar1
            foo2: bar2
          hosts_entry: '

            192.168.24.1 standalone.localdomain standalone

            192.168.24.1 standalone.ctlplane.localdomain standalone.ctlplane

            '
          net_vip_map:
            ctlplane: 192.168.24.1
            ctlplane_subnet: 192.168.24.1/24
            ctlplane_uri: 192.168.24.1
            redis: 192.168.24.1
            ovn_dbs: 192.168.24.1
          network_virtual_ips:
            ctlplane:
              index: 1
              ip_address: 192.168.24.1
          network_cidrs:
            External_cidr: 192.168.24.2/24
          networks: null
          nova_additional_cell: false
          ping_test_ips:
            Standalone: 192.168.24.1
          primary_role_name: Standalone
          role_networks:
            - Internal
          service_configs:
            foo: bar3
          service_names:
            - ca_certs
            - ceph_client
            - ceph_mds
            - ceph_mgr
            - ceph_mon
            - ceph_rgw
            - ceph_osd
            - certmonger_user
            - clustercheck
            - container_image_prepare
            - logrotate_crond
            - docker
            - docker_registry
            - glance_api
            - haproxy
            - iscsid
            - kernel
            - keystone
            - manila_api
            - manila_backend_cephfs
            - manila_scheduler
            - manila_share
            - memcached
            - mysql
            - mysql_client
            - neutron_api
            - neutron_plugin_ml2_ovn
            - nova_api
            - nova_compute
            - nova_conductor
            - nova_libvirt
            - nova_metadata
            - nova_migration_target
            - nova_scheduler
            - nova_vnc_proxy
            - ovn_controller
            - ovn_dbs
            - ovn_metadata
            - openstack_clients
            - oslo_messaging_notify
            - oslo_messaging_rpc
            - pacemaker
            - placement
            - podman
            - snmp
            - sshd
            - chrony
            - timezone
            - logrotate_tmpwatch
            - tripleo_firewall
            - tripleo_packages
            - tuned
          service_net_map:
            aodh_api_network: ctlplane
            apache_network: ctlplane
            barbican_api_network: ctlplane
            bindnetwork: ctlplane
            ceph_cluster_network: ctlplane
            ceph_grafana_network: ctlplane
            ceph_mon_network: ctlplane
            ceph_rgw_network: ctlplane
            cinder_api_network: ctlplane
            cinder_iscsi_network: ctlplane
            designate_api_network: ctlplane
            docker_registry_network: ctlplane
            ec2_api_metadata_network: ctlplane
            ec2_api_network: ctlplane
            etcd_network: ctlplane
            ganesha_network: ctlplane
            glance_api_network: ctlplane
            gnocchi_api_network: ctlplane
            haproxy_network: ctlplane
            heat_api_cfn_network: ctlplane
            heat_api_cloudwatch_network: ctlplane
            heat_api_network: ctlplane
            horizon_network: ctlplane
            ironic_api_network: ctlplane
            ironic_inspector_network: ctlplane
            ironic_network: ctlplane
            keystone_admin_api_network: ctlplane
            keystone_public_api_network: ctlplane
            manila_api_network: ctlplane
            memcached_network: ctlplane
            metrics_qdr_network: ctlplane
            mistral_api_network: ctlplane
            mongodb_network: ctlplane
            mysql_network: ctlplane
            neutron_api_network: ctlplane
            neutron_tenant_network: ctlplane
            nova_api_network: ctlplane
            nova_libvirt_network: ctlplane
            nova_metadata_network: ctlplane
            nova_vnc_proxy_network: ctlplane
            novajoin_network: ctlplane
            octavia_api_network: ctlplane
            openshift_infra_network: ctlplane
            openshift_master_network: ctlplane
            oslo_messaging_notify_network: ctlplane
            oslo_messaging_rpc_network: ctlplane
            ovn_dbs_network: ctlplane
            pacemaker_network: ctlplane
            pacemaker_remote_network: ctlplane
            panko_api_network: ctlplane
            placement_network: ctlplane
            public_network: ctlplane
            qdr_network: ctlplane
            rabbitmq_network: ctlplane
            redis_network: ctlplane
            sahara_api_network: ctlplane
            snmpd_network: ctlplane
            standalone_hostname_resolve_network: ctlplane
            swift_proxy_network: ctlplane
            swift_storage_network: ctlplane
            tacker_api_network: ctlplane
            zaqar_api_network: ctlplane
          stack_action: CREATE
          stack_update_type: ''
          tripleo_role_name: Standalone
          validate_controllers_icmp: true
          validate_fqdn: false
          validate_gateways_icmp: true
          validate_ntp: true
      Standalone:
        hosts:
          centos8: {}
          centos7: {}
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - verify
    - destroy

verifier:
  name: testinfra
