---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Async creation of Keystone project
  os_project:
    cloud: "{{ tripleo_keystone_resources_cloud_name }}"
    name: "{{ tripleo_keystone_resources_project }}"
    domain_id: default
    state: present
  async: 60
  poll: 0
  register: tripleo_keystone_resources_project_results
  loop: "{{ batched_tripleo_keystone_resources_projects }}"
  loop_control:
    loop_var: tripleo_keystone_resources_project

- name: Check Keystone project status
  async_status:
    jid: "{{ tripleo_keystone_resources_project_async_result_item.ansible_job_id }}"
  loop: "{{ tripleo_keystone_resources_project_results.results }}"
  loop_control:
    loop_var: "tripleo_keystone_resources_project_async_result_item"
  register: tripleo_keystone_resources_project_async_poll_results
  until: tripleo_keystone_resources_project_async_poll_results.finished
  retries: 30
