---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Converge
  hosts: all
  pre_tasks:
    - name: Create puppet hieradata directory
      file:
        path: /etc/puppet/hieradata
        state: directory

    - name: Set mock network ip facts
      set_fact:
        CTRLPlane_ip: 192.168.24.2
        ctlplane_ip: 192.168.24.2
        Internal_ip: 192.168.25.2

  tasks:
    - name: Create hieradata from templates
      include_role:
        name: tripleo-hieradata
        tasks_from: hieradata_vars.yaml
      vars:
        hieradata_templates_list:
          - all_nodes
          - bootstrap_node
          - cloud_domain
          - extraconfig
          - fqdn
          - net_ip_map
          - service_configs
          - service_names
          - vip_data
          - ovn_chassis_mac_map
