---
galaxy_info:
  author: OpenStack
  description: TripleO OpenStack Role -- tripleo_metrics_qdr
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: 2.7
  platforms:
    - name: CentOS
      versions:
        - 8
  galaxy_tags:
    - tripleo
dependencies: []
