---
driver:
  name: podman

log: true

platforms:
  - name: centos
    hostname: centos
    image: centos/centos:stream8
    registry:
      url: quay.io
    dockerfile: Dockerfile
    pkg_extras: python*setuptools
    volumes:
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
      - /etc/pki/rpm-gpg:/etc/pki/rpm-gpg
      - /opt/yum.repos.d:/etc/yum.repos.d:rw
      - /etc/dnf/vars:/etc/dnf/vars
    privileged: true
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
    ulimits: &ulimit
      - host

provisioner:
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          centos:
            ansible_python_interpreter: /usr/bin/python3
        vars:
          # use a tmp hosts path since /etc/hosts isn't writeable in the
          # molecule test containers
          tripleo_hosts_entries_hosts_path: /tmp/hosts
          tripleo_hosts_entries_overcloud_hosts_entries:
            - 192.168.24.1 centos.localdomain centos
            - 192.168.24.1 centos.ctlplane.localdomain centos.ctlplane
            - 172.17.0.1 centos.internalapi.localdomain centos.internalapi
          tripleo_hosts_entries_undercloud_hosts_entries: []
          tripleo_hosts_entries_extra_hosts_entries: []
          tripleo_stack_name: overcloud
          plan: overcloud
        children:
          allovercloud:
            hosts:
              centos:
                hostname_resolve_network: ctlplane
                ctlplane_ip: 192.168.24.1
                internal_api_ip: 172.17.0.1

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - verify
    - destroy

verifier:
  name: ansible
