---
# Copyright 2020 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# All variables intended for modification should be placed in this file.

# All variables within this role should have a prefix of "tripleo_container_standalone"
tripleo_container_standalone_debug: "{{ (ansible_verbosity | int) >= 2 | bool }}"

tripleo_container_standalone_hide_sensitive_logs: true

# Service name. Use for creating directories, container labels, etc
tripleo_container_standalone_service : ""
# Directory for kolla config files
tripleo_container_standalone_kolla_config_dir: /var/lib/kolla/config_files
# Directory for container startup configs
tripleo_container_standalone_container_startup_config_dir: /var/lib/tripleo-config/container-startup-config
# Hash with keys of container name and value of YAML kolla config file.
tripleo_container_standalone_kolla_config_files: {}
# Hash with keys of container name and value of YAML container definition
tripleo_container_standalone_container_defs: {}

# List of common volumes that can be included in the template of a container
# definition to include the most common volumes.
tripleo_container_standalone_common_volumes:
  - /etc/hosts:/etc/hosts:ro
  - /etc/localtime:/etc/localtime:ro
  # OpenSSL trusted CAs
  - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
  - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
  - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
  - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
  - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
  # Syslog socket
  - /dev/log:/dev/log
  # required for bootstrap_host_exec
  - /etc/puppet:/etc/puppet:ro

# List of volumes included when internal tls is enabled
tripleo_container_standalone_internal_tls_volumes:
  - /etc/pki/tls/certs/httpd:/etc/pki/tls/certs/httpd:ro
  - /etc/pki/tls/private/httpd:/etc/pki/tls/private/httpd:ro

# Internal TLS vars. These vars are not prefixed with the role name as they are
# intended to be set from other services/roles.
tripleo_enable_internal_tls: false
tripleo_internal_tls_ca_file: /etc/ipa/ca.crt

tripleo_container_standalone_volumes: "{{
    tripleo_enable_internal_tls |
      ternary(
        tripleo_container_standalone_common_volumes +
          tripleo_container_standalone_internal_tls_volumes +
          [tripleo_internal_tls_ca_file ~ ':' ~ tripleo_internal_tls_ca_file ~ ':ro'],
        tripleo_container_standalone_common_volumes)
  }}"

tripleo_debug: False
tripleo_deploy_identifier: ''
