---
# Copyright 2022 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- tags: down
  become: true
  environment:
    OS_CLOUD: >-
      {% if auth_cloud_name_set %}{{ tripleo_nova_compute_auth_cloud_name }}{% else %}{{ tripleo_nova_compute_root_stack_name }}{% endif %}
  block:
    # Some tasks are running from the Undercloud which has
    # the OpenStack clients installed.
    - name: Get nova-compute service ID
      command: openstack compute service list --service nova-compute --column ID --column Host --format yaml
      register: nova_compute_service_result
      delegate_to: "{{ groups['Undercloud'] | first }}"
      check_mode: false
      changed_when: false

    - name: Set fact for nova_compute services
      set_fact:
        nova_compute_service: "{{ nova_compute_service_result.stdout | from_yaml | selectattr('Host', 'match', ansible_facts['fqdn'] ~ '.*') | list }}"
      delegate_to: "{{ groups['Undercloud'] | first }}"
      check_mode: false

    - name: Check search output
      fail:
        msg: >-
          Found multiple `{{ ansible_facts['fqdn'] }}`, which is unexpected.
          This means that the FQDN of the selected device to disable is
          either wrong or is sharing a name with another host, which is
          also wrong. Please correct this issue before continuing. Nova
          service list return data can be found here
          -> {{ nova_compute_service }}.
      when:
        - (nova_compute_service | length) > 1

    - name: Disable nova services
      when:
        - (nova_compute_service | length) == 1
      block:
        - name: Disable nova-compute service
          command: openstack compute service set {{ nova_compute_service[0].Host }} nova-compute --disable
          delegate_to: "{{ groups['Undercloud'] | first }}"
          check_mode: false
          when:
            - not tripleo_nova_compute_additional_cell|bool

        - name: Stop nova-compute container
          service:
            name: tripleo_nova_compute
            state: stopped
            enabled: false
          become: true
          register: stop_nova_compute
          failed_when: "('msg' in stop_nova_compute and
            'Could not find the requested service tripleo_nova_compute' not in stop_nova_compute.msg) or
            ('rc' in stop_nova_compute and stop_nova_compute.rc != 0)"

        - name: Delete nova-compute service
          command: openstack compute service delete {{ nova_compute_service[0].ID }}
          delegate_to: "{{ groups['Undercloud'] | first }}"
          check_mode: false
