---
# We don't want to get false positive on subscription manager network
# issues, hence the logic in the retries/until.
- name: get current release settings
  command: 'subscription-manager release --show'
  register: subscribed_release
  ignore_errors: true
  retries: 5
  delay: 3
  until: ('ConnectionRefusedError' not in subscribed_release.stderr and subscribed_release is failed) or subscribed_release is success

- name: fails if not registered
  fail:
    msg: >-
      Your environment is not subscribed!
      If it is expected, please set SkipRhelEnforcement to true in the heat
      parameter.
      You can also disable it in the role, see rhsm_enforce role parameter.
      If this is unexpected, you have to subscribe this node and
      ensure that RHEL is pinned to {{ tripleo_redhat_enforce_os }} as
      this is the only version supported for {{ tripleo_redhat_enforce_osp }}.
  when:
    - subscribed_release is failed
    - ( 'This system is not yet registered' in subscribed_release.stderr )

- name: unknown failure during call to subscription-manager
  fail:
    msg: >-
      Unknow failure during 'subscription-manager release --show':
      {{ subscribed_release.stderr }}
  when:
    - subscribed_release is failed
    - ( 'This system is not yet registered' not in subscribed_release.stderr )

- name: fails if the release is not correct
  fail:
    msg: >-
      OSP{{ tripleo_redhat_enforce_osp }} is only supported with Red Hat {{ tripleo_redhat_enforce_os }}.
      Please make sure to pin rhel to {{ tripleo_redhat_enforce_os }} using:
      subscription-manager release --set={{ tripleo_redhat_enforce_os }}.
      You can then proceed with the update. You can also disable it in the
      role, see rhsm_enforce role parameter, if this is expected.
  when: tripleo_redhat_enforce_os not in subscribed_release.stdout
