---
- name: Verify
  hosts: all
  tasks:
    - name: Ensure we activated GSSAPI
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "GSSAPIAuthentication yes"
        state: present
      register: gssapi
      failed_when:
        - gssapi is changed
