---
# Copyright 2022 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

tripleo_controller_group_name: "{{ controller_group_name | default('Controller') }}"
tripleo_compute_group_name: "{{ compute_group_name | default('Compute') }}"

tripleo_snapshot_revert_audit_size: 512M
tripleo_snapshot_revert_home_size: 512M
tripleo_snapshot_revert_log_size: 1G
tripleo_snapshot_revert_root_size: 2G
tripleo_snapshot_revert_srv_size: 512M
tripleo_snapshot_revert_var_size: 3G

# These parameters ensure that nodes are taken out from Pacemaker cluster
# before taking a snapshot, one node at a time to not cause any downtimes.
tripleo_snapshot_revert_snapshot_inactive_nodes: "{{ snapshot_inactive_nodes | default('true') }}"
tripleo_snapshot_revert_pcs_timeout: 3600
